//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AudioStreaming.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class AudioDBEntities : DbContext
    {
        public AudioDBEntities()
            : base("name=AudioDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_Audio> tbl_Audio { get; set; }
    
        public virtual ObjectResult<sp_AudioPagination_Result> sp_AudioPagination(Nullable<int> sTARTROWINDEX, Nullable<int> mAXIMUMROWS)
        {
            var sTARTROWINDEXParameter = sTARTROWINDEX.HasValue ?
                new ObjectParameter("STARTROWINDEX", sTARTROWINDEX) :
                new ObjectParameter("STARTROWINDEX", typeof(int));
    
            var mAXIMUMROWSParameter = mAXIMUMROWS.HasValue ?
                new ObjectParameter("MAXIMUMROWS", mAXIMUMROWS) :
                new ObjectParameter("MAXIMUMROWS", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_AudioPagination_Result>("sp_AudioPagination", sTARTROWINDEXParameter, mAXIMUMROWSParameter);
        }
    
        public virtual ObjectResult<sp_SearchTrack_Result> sp_SearchTrack(string searchTrack)
        {
            var searchTrackParameter = searchTrack != null ?
                new ObjectParameter("SearchTrack", searchTrack) :
                new ObjectParameter("SearchTrack", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_SearchTrack_Result>("sp_SearchTrack", searchTrackParameter);
        }
    
        public virtual ObjectResult<sp_SongListByArtist_Result> sp_SongListByArtist(string artistName)
        {
            var artistNameParameter = artistName != null ?
                new ObjectParameter("ArtistName", artistName) :
                new ObjectParameter("ArtistName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_SongListByArtist_Result>("sp_SongListByArtist", artistNameParameter);
        }
    }
}
